{{- if .Values.collectionServer.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aiservice-monitoring.fullname" . }}-server
  namespace: {{ include "aiservice-monitoring.namespace" . }}
  labels:
    {{- include "aiservice-monitoring.labels" . | nindent 4 }}
    app.kubernetes.io/component: collection-server
{{- end }}
