{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aiservice-monitoring.fullname" . }}-frontend
  namespace: {{ include "aiservice-monitoring.namespace" . }}
  labels:
    {{- include "aiservice-monitoring.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "aiservice-monitoring.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
{{- end }}
