package lite

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// PDF page dimensions: A4 in points (1 pt = 1/72 inch).
const (
	pdfPageW = 595.28
	pdfPageH = 841.89
	pdfLeft  = 50.0
	pdfRight = 545.0
)

// GeneratePDF creates a single-file PDF diagnostic report.
// It uses a pure-Go minimal PDF/1.4 writer — no external binaries are required.
// Returns the path to the generated file.
func (g *ReportGenerator) GeneratePDF(outputDir string, startTime time.Time) (string, error) {
	pending, _ := g.buf.PendingCount()
	duration := time.Since(startTime)
	hostname, _ := os.Hostname()
	now := time.Now()

	filename := fmt.Sprintf("aitop-lite-report-%s.pdf", now.Format("2006-01-02-150405"))
	outputPath := filepath.Join(outputDir, filename)

	data := buildReportPDF(hostname, startTime, now, duration, int(pending))
	if err := os.WriteFile(outputPath, data, 0644); err != nil {
		return "", fmt.Errorf("write PDF: %w", err)
	}
	return outputPath, nil
}

// buildReportPDF assembles the PDF bytes for the diagnostic report.
func buildReportPDF(hostname string, startTime, now time.Time, duration time.Duration, items int) []byte {
	p := &pdfPage{}

	// Title + divider
	p.text(pdfLeft, 790, "F2", 16, "AITOP Lite - Performance Diagnostic Report")
	p.hline(pdfLeft, 779, pdfRight, 1.0)

	// Metadata block
	p.color(0.33, 0.33, 0.33)
	p.text(pdfLeft, 763, "F1", 9, "Host: "+hostname)
	p.text(pdfLeft, 751, "F1", 9, "Period: "+startTime.Format("2006-01-02 15:04")+" ~ "+now.Format("2006-01-02 15:04"))
	p.text(pdfLeft, 739, "F1", 9, "Duration: "+formatDuration(duration))
	p.text(pdfLeft, 727, "F1", 9, "Generated: "+now.Format("2006-01-02 15:04:05"))
	p.color(0, 0, 0)

	// Collection Summary section
	p.text(pdfLeft, 706, "F2", 12, "Collection Summary")
	p.hline(pdfLeft, 700, pdfRight, 0.5)

	kpis := [][2]string{
		{"Total Items", fmt.Sprintf("%d", items)},
		{"Duration", formatDuration(duration)},
		{"Retention", "7d"},
		{"Status", "OK"},
	}
	kpiX := [4]float64{pdfLeft, 181, 312, 443}
	for i, k := range kpis {
		p.text(kpiX[i], 680, "F2", 18, k[1])
		p.color(0.44, 0.44, 0.44)
		p.text(kpiX[i], 667, "F1", 8, k[0])
		p.color(0, 0, 0)
	}

	// Collector Status section
	p.text(pdfLeft, 645, "F2", 12, "Collector Status")
	p.hline(pdfLeft, 639, pdfRight, 0.5)

	p.fillRect(pdfLeft, 624, pdfRight-pdfLeft, 13, 0.93, 0.93, 0.96)
	p.color(0.15, 0.15, 0.15)
	p.text(pdfLeft+4, 629, "F2", 8, "Collector")
	p.text(168, 629, "F2", 8, "Type")
	p.text(226, 629, "F2", 8, "Status")
	p.text(306, 629, "F2", 8, "Description")
	p.color(0, 0, 0)

	collectors := [][4]string{
		{"it-os", "IT", "Active", "OS metrics (CPU, Memory, Disk, Network)"},
		{"it-web", "IT", "Active", "Web server (Nginx, Apache) metrics"},
		{"it-was", "IT", "Active", "WAS (Tomcat, JBoss) metrics"},
		{"it-db", "IT", "Active", "Database (PostgreSQL, MySQL) metrics"},
		{"ai-gpu", "AI", "Detected", "GPU utilization (NVIDIA DCGM)"},
		{"ai-llm", "AI", "Detected", "LLM performance (TTFT, TPS, tokens)"},
	}
	rowY := 612.0
	for _, c := range collectors {
		p.text(pdfLeft+4, rowY, "F1", 8, c[0])
		p.text(168, rowY, "F1", 8, c[1])
		p.text(226, rowY, "F1", 8, c[2])
		p.text(306, rowY, "F1", 8, c[3])
		rowY -= 13
	}

	// Recommendations section
	secY := rowY - 8
	p.text(pdfLeft, secY, "F2", 12, "Recommendations")
	p.hline(pdfLeft, secY-6, pdfRight, 0.5)

	recHdrY := secY - 22
	p.fillRect(pdfLeft, recHdrY, pdfRight-pdfLeft, 13, 0.93, 0.93, 0.96)
	p.color(0.15, 0.15, 0.15)
	p.text(pdfLeft+4, recHdrY+4, "F2", 8, "#")
	p.text(78, recHdrY+4, "F2", 8, "Category")
	p.text(180, recHdrY+4, "F2", 8, "Finding")
	p.text(336, recHdrY+4, "F2", 8, "Action")
	p.color(0, 0, 0)

	recs := [][4]string{
		{"1", "Performance", "Data collected for analysis", "Review XLog distribution for slow transactions"},
		{"2", "AI Service", "LLM metrics captured", "Check TTFT P95 against SLO threshold (2s)"},
		{"3", "Infrastructure", "Resource utilization tracked", "Identify CPU/Memory bottlenecks from trends"},
	}
	recRowY := recHdrY - 10
	for _, r := range recs {
		p.text(pdfLeft+4, recRowY, "F1", 8, r[0])
		p.text(78, recRowY, "F1", 8, r[1])
		p.text(180, recRowY, "F1", 8, r[2])
		p.text(336, recRowY, "F1", 8, r[3])
		recRowY -= 13
	}

	// Footer
	p.hline(pdfLeft, 62, pdfRight, 0.5)
	p.color(0.55, 0.55, 0.55)
	p.text(pdfLeft, 52, "F1", 7,
		fmt.Sprintf("Generated by AITOP Lite v1.0 - %s", now.Format("2006-01-02 15:04:05")))
	p.text(pdfLeft, 41, "F1", 7,
		fmt.Sprintf("Report from %d collected items over %s.", items, formatDuration(duration)))

	return p.assemble()
}

// ── pdfPage: minimal PDF/1.4 content-stream builder ──────────────────────────

type pdfPage struct {
	cs bytes.Buffer // PDF content stream
}

func (p *pdfPage) wr(format string, args ...interface{}) {
	fmt.Fprintf(&p.cs, format+"\n", args...)
}

// color sets the fill/text colour (r, g, b in 0..1).
func (p *pdfPage) color(r, g, b float64) {
	p.wr("%.3f %.3f %.3f rg", r, g, b)
}

// text renders string s at (x, y) with font key f and point size sz.
// f must be "F1" (Helvetica) or "F2" (Helvetica-Bold).
func (p *pdfPage) text(x, y float64, f string, sz float64, s string) {
	p.wr("BT /%s %.2f Tf %.2f %.2f Td (%s) Tj ET", f, sz, x, y, pdfEscape(s))
}

// hline draws a horizontal rule from x1 to x2 at height y with line-width lw.
func (p *pdfPage) hline(x1, y, x2, lw float64) {
	p.wr("%.2f w %.2f %.2f m %.2f %.2f l S", lw, x1, y, x2, y)
}

// fillRect draws a filled rectangle with background colour (r,g,b).
// x,y is the bottom-left corner in PDF coordinates (y increases upward).
// Fill colour is reset to black afterwards.
func (p *pdfPage) fillRect(x, y, w, h, r, g, b float64) {
	p.wr("%.3f %.3f %.3f rg %.2f %.2f %.2f %.2f re f 0.000 0.000 0.000 rg",
		r, g, b, x, y, w, h)
}

// pdfEscape escapes PDF string-literal special characters and drops non-ASCII bytes.
func pdfEscape(s string) string {
	var b strings.Builder
	b.Grow(len(s))
	for _, r := range s {
		switch r {
		case '\\':
			b.WriteString("\\\\")
		case '(':
			b.WriteString("\\(")
		case ')':
			b.WriteString("\\)")
		default:
			if r >= 0x20 && r <= 0x7E {
				b.WriteRune(r)
			}
		}
	}
	return b.String()
}

// assemble builds the final PDF/1.4 binary from the accumulated content stream.
// Object layout:
//
//	1 Catalog  2 Pages  3 Font/F1  4 Font/F2  5 Page  6 Content stream
func (p *pdfPage) assemble() []byte {
	cs := p.cs.Bytes()

	var out bytes.Buffer
	offsets := make([]int, 0, 6)

	put := func(s string) { out.WriteString(s) }
	putf := func(f string, a ...interface{}) { fmt.Fprintf(&out, f, a...) }

	// PDF file header; binary bytes after %PDF trigger binary-safe transport.
	put("%PDF-1.4\n%\xe2\xe3\xcf\xd3\n")

	// Object 1 — Catalog
	offsets = append(offsets, out.Len())
	put("1 0 obj\n<</Type /Catalog /Pages 2 0 R>>\nendobj\n")

	// Object 2 — Pages tree
	offsets = append(offsets, out.Len())
	put("2 0 obj\n<</Type /Pages /Kids [3 0 R] /Count 1>>\nendobj\n")

	// Object 3 — Font F1 (Helvetica regular)
	offsets = append(offsets, out.Len())
	put("3 0 obj\n<</Type /Font /Subtype /Type1 /BaseFont /Helvetica" +
		" /Encoding /WinAnsiEncoding>>\nendobj\n")

	// Object 4 — Font F2 (Helvetica-Bold)
	offsets = append(offsets, out.Len())
	put("4 0 obj\n<</Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold" +
		" /Encoding /WinAnsiEncoding>>\nendobj\n")

	// Object 5 — Page
	offsets = append(offsets, out.Len())
	putf("5 0 obj\n<</Type /Page /Parent 2 0 R"+
		" /MediaBox [0 0 %.2f %.2f]"+
		" /Contents 6 0 R"+
		" /Resources <</Font <</F1 3 0 R /F2 4 0 R>>>>>>\nendobj\n",
		pdfPageW, pdfPageH)

	// Object 6 — Content stream
	offsets = append(offsets, out.Len())
	putf("6 0 obj\n<</Length %d>>\nstream\n", len(cs))
	out.Write(cs)
	put("endstream\nendobj\n")

	// Cross-reference table (each entry is exactly 20 bytes per PDF spec)
	xrefOff := out.Len()
	n := len(offsets) + 1 // includes free object 0
	putf("xref\n0 %d\n", n)
	put("0000000000 65535 f \n") // object 0 (free head)
	for _, off := range offsets {
		putf("%010d 00000 n \n", off)
	}

	// Trailer
	putf("trailer\n<</Size %d /Root 1 0 R>>\nstartxref\n%d\n", n, xrefOff)
	put("%%EOF\n")

	return out.Bytes()
}
