package lite

import (
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"time"

	"github.com/aurakimjh/aiservice-monitoring/agent/internal/buffer"
)

// ReportGenerator creates diagnostic reports from collected data.
type ReportGenerator struct {
	buf    *buffer.Buffer
	logger *slog.Logger
}

// NewReportGenerator creates a report generator.
func NewReportGenerator(buf *buffer.Buffer, logger *slog.Logger) *ReportGenerator {
	return &ReportGenerator{buf: buf, logger: logger}
}

// GenerateHTML creates a single-file HTML diagnostic report.
// Returns the path to the generated file.
func (g *ReportGenerator) GenerateHTML(outputDir string, startTime time.Time) (string, error) {
	pending, _ := g.buf.PendingCount()
	duration := time.Since(startTime)
	hostname, _ := os.Hostname()
	now := time.Now()

	filename := fmt.Sprintf("aitop-lite-report-%s.html", now.Format("2006-01-02-150405"))
	outputPath := filepath.Join(outputDir, filename)

	html := fmt.Sprintf(`<!DOCTYPE html>
<html lang="ko">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>AITOP Lite Diagnostic Report</title>
<style>
*{margin:0;padding:0;box-sizing:border-box}
body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;background:#fff;color:#24292f;max-width:900px;margin:0 auto;padding:2rem}
h1{font-size:1.75rem;border-bottom:2px solid #0969da;padding-bottom:.5rem;margin-bottom:1.5rem}
h2{font-size:1.25rem;color:#0969da;margin:1.5rem 0 .75rem;padding-bottom:.25rem;border-bottom:1px solid #d0d7de}
.meta{background:#f6f8fa;border:1px solid #d0d7de;border-radius:6px;padding:1rem;margin-bottom:1.5rem;font-size:.875rem}
.meta dt{font-weight:600;display:inline}
.meta dd{display:inline;margin:0 1.5rem 0 .25rem}
.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:.75rem;margin-bottom:1.5rem}
.kpi{background:#f6f8fa;border:1px solid #d0d7de;border-radius:6px;padding:1rem;text-align:center}
.kpi .label{font-size:.75rem;color:#57606a}
.kpi .value{font-size:1.5rem;font-weight:700;color:#24292f}
table{width:100%%;border-collapse:collapse;font-size:.875rem;margin-bottom:1.5rem}
th{background:#f6f8fa;text-align:left;padding:.5rem;border:1px solid #d0d7de;font-weight:600}
td{padding:.5rem;border:1px solid #d0d7de}
.footer{margin-top:2rem;text-align:center;font-size:.75rem;color:#8b949e;border-top:1px solid #d0d7de;padding-top:1rem}
</style>
</head>
<body>
<h1>AITOP Lite — Performance Diagnostic Report</h1>

<div class="meta">
<dt>Host:</dt><dd>%s</dd>
<dt>Period:</dt><dd>%s ~ %s</dd>
<dt>Duration:</dt><dd>%s</dd>
<dt>Generated:</dt><dd>%s</dd>
</div>

<h2>Collection Summary</h2>
<div class="grid">
  <div class="kpi"><div class="label">Total Items</div><div class="value">%d</div></div>
  <div class="kpi"><div class="label">Duration</div><div class="value">%s</div></div>
  <div class="kpi"><div class="label">Retention</div><div class="value">7d</div></div>
  <div class="kpi"><div class="label">Status</div><div class="value">OK</div></div>
</div>

<h2>Collector Status</h2>
<table>
<tr><th>Collector</th><th>Type</th><th>Status</th><th>Description</th></tr>
<tr><td>it-os</td><td>IT</td><td>Active</td><td>OS metrics (CPU, Memory, Disk, Network)</td></tr>
<tr><td>it-web</td><td>IT</td><td>Active</td><td>Web server (Nginx, Apache) metrics</td></tr>
<tr><td>it-was</td><td>IT</td><td>Active</td><td>WAS (Tomcat, JBoss) metrics</td></tr>
<tr><td>it-db</td><td>IT</td><td>Active</td><td>Database (PostgreSQL, MySQL) metrics</td></tr>
<tr><td>ai-gpu</td><td>AI</td><td>Detected</td><td>GPU utilization (NVIDIA DCGM)</td></tr>
<tr><td>ai-llm</td><td>AI</td><td>Detected</td><td>LLM performance (TTFT, TPS, tokens)</td></tr>
</table>

<h2>Recommendations</h2>
<table>
<tr><th>#</th><th>Category</th><th>Finding</th><th>Action</th></tr>
<tr><td>1</td><td>Performance</td><td>Data collected for analysis</td><td>Review XLog distribution for slow transactions</td></tr>
<tr><td>2</td><td>AI Service</td><td>LLM metrics captured</td><td>Check TTFT P95 against SLO threshold (2s)</td></tr>
<tr><td>3</td><td>Infrastructure</td><td>Resource utilization tracked</td><td>Identify CPU/Memory bottlenecks from trends</td></tr>
</table>

<div class="footer">
Generated by AITOP Lite v1.0 — %s<br>
This report was generated from %d collected data items over %s.
</div>
</body>
</html>`,
		hostname,
		startTime.Format("2006-01-02 15:04"),
		now.Format("2006-01-02 15:04"),
		formatDuration(duration),
		now.Format("2006-01-02 15:04:05"),
		pending,
		formatDuration(duration),
		now.Format("2006-01-02 15:04:05"),
		pending,
		formatDuration(duration),
	)

	if err := os.WriteFile(outputPath, []byte(html), 0644); err != nil {
		return "", fmt.Errorf("write report: %w", err)
	}

	return outputPath, nil
}
